5 implement supplier poduct add
G-Mart-Online/gmart-seller-supplier-portal pull request #7
Opened 2024-11-17 20:06 UTC by salinda-yasas-99

2024-11-24 06:12 UTC, lakshankd requested changes

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +        message.error("Please upload at least 6 images.");
remove this message

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +        message.error(
remove this alert

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +        image6: fileList[5].originFileObj,
make this an array

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +      style={{
move this to a separate css file (supplier-styles.css)

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +        }}
move this to a separate css file (supplier-styles.css)

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +                style={{ maxWidth: 1000 }}
move this to a separate css file (supplier-styles.css)

2024-11-24 06:12 UTC, lakshankd commented on src/app/supplier/products/add/page.js
> +                    style={{ width: 150 }}
move this to a separate css file (supplier-styles.css).....

2024-11-24 06:12 UTC, lakshankd commented on src/components/supplier/SupplierPageTitle.js
> +      style={{ height: "100%" }}
move this to a separate css file (supplier-styles.css)

2024-11-24 06:12 UTC, lakshankd commented on src/components/supplier/SupplierPageTitle.js
> +      <Title level={4} style={{ margin: 0 }}>
move this to a separate css file (supplier-styles.css)

2024-11-26 01:58 UTC, salinda-yasas-99 commented on src/app/supplier/products/add/page.js
> +                style={{ maxWidth: 1000 }}
check the logic first

2024-11-26 01:58 UTC, salinda-yasas-99 commented on src/app/supplier/products/add/page.js
> +        image6: fileList[5].originFileObj,
sloved

2024-12-03 16:01 UTC, lakshankd approved these changes

2024-12-03 16:02 UTC, merged